FROM docker.io/library/debian:latest

RUN set -eux; \
	apt-get update; \
    DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends man python3 python3-venv python3-systemd; \
    rm -rf /var/lib/apt/lists/*

COPY . /opt/jsonlogalert

WORKDIR /opt/jsonlogalert

RUN set -eux; \
    mkdir /tmp/pycache; \
    chmod o-rwx /tmp/pycache

ENV PYTHONPYCACHEPREFIX=/tmp/pycache

# Set to install from source; unset to install from latest GitHub release
ENV SRCDIR=/opt/jsonlogalert

RUN set -eux; \
    ./install.sh

ENV PATH="/usr/local/bin:$PATH"

ENTRYPOINT ["jsonlogalert"]
