FROM docker.io/library/debian:latest

RUN set -eux; \
	apt-get update; \
    DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends man python3 python3-venv python3-systemd curl; \
    rm -rf /var/lib/apt/lists/*

RUN set -eux; \
    mkdir /tmp/pycache; \
    chmod o-rwx /tmp/pycache

ENV PYTHONPYCACHEPREFIX=/tmp/pycache

# Set to install from source; unset to install from latest GitHub release
ENV SRCDIR=/opt/jsonlogalert

COPY ./install.sh /root
COPY . /opt/jsonlogalert

# Install from outside SRCDIR to make sure we're
# not taking relative paths for granted.
WORKDIR /root

RUN set -eux; \
    ./install.sh -d

ENV PATH="/usr/local/bin:$PATH"

ENTRYPOINT ["jsonlogalert"]
