#!/bin/sh

# Combine 'install_*.sh' and functions from https://github.com/client9/shlib.

set -e

BUILD_DIR=$(readlink -f ./build)

git_clone()
{
	giturl="$1"
	gitrepo="${giturl##*/}"   # foo.git
	gitrepo="${gitrepo%.git}" # foo

	[ -d "$gitrepo" ] || git clone "$giturl"
}

mkdir -p "$BUILD_DIR"

(cd "$BUILD_DIR" && git_clone https://github.com/client9/shlib.git)

if ! test -d "$BUILD_DIR/shlib"; then
	echo "$BUILD_DIR/shlib: failed to clone" 1>&2
	exit 1
fi

echo "#!/usr/bin/env sh"
echo
echo "# DO NOT EDIT THIS FILE DIRECTLY!"
echo "# IT IS THE COMBINATION OF 'makeinstall.sh/*.sh' and functions from"
echo "# https://github.com/client9/shlib.git"

grep -v '^\s*#' makeinstallsh/install_head.sh

(
	cd "$BUILD_DIR/shlib"

	cat \
		license.sh \
		is_command.sh \
		echoerr.sh \
		log.sh \
		uname_os.sh \
		uname_arch.sh \
		uname_os_check.sh \
		uname_arch_check.sh \
		untar.sh \
		http_download.sh \
		github_release.sh \
		license_end.sh |
		grep -v '^#' | grep -v ' #' | tr -s '\n'
)

grep -v '^\s*#' makeinstallsh/install_main.sh | tr -s '\n'
